### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vincenzoraco** [aurelia/binding#148]
app.html

```
<template>
    <router-view></router-view>
</template>
```

global.html

```
<template>
    <div>
        <header>
            <div class="container">
                <router-view name="menu"></router-view>
            </div>
        </header>

        <router-view></router-view>
        <router-view name="footer"></router-view>
    </div>
</template>
```

global.js

```
export class Static {
    configureRouter (config, router) {
        config.map([
            {
                route: '',
                viewPorts: {
                    menu: {
                        moduleId: 'static/menu',
                        nav: false
                    },
                    default: {
                        moduleId: 'static/homepage',
                        nav: true,
                        title: 'Homepage'
                    },
                    footer: {
                        moduleId: 'static/footer',
                        nav: false
                    }
                }
            }
        ])
        this.router = router;
    }
}

```

Adding the third `router-view` on the child router, I got this error:

```
ERROR [app-router] RangeError: Maximum call stack size exceeded
    at ObserverLocator.createObserversLookup (http://localhost:8000/jspm_packages/github/aurelia/binding@0.8.5/aurelia-binding.js:4440:7)
    at ObserverLocator.getOrCreateObserversLookup (http://localhost:8000/jspm_packages/github/aurelia/binding@0.8.5/aurelia-binding.js:4436:40)
    at new BehaviorInstance (http://localhost:8000/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:2042:53)
    at HtmlBehaviorResource.create (http://localhost:8000/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:2682:30)
    at applyInstructions (http://localhost:8000/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:1241:33)
    at ViewFactory.create (http://localhost:8000/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:1407:9)
    at HtmlBehaviorResource.create (http://localhost:8000/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:2693:47)
    at applyInstructions (http://localhost:8000/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:1241:33)
    at ViewFactory.create (http://localhost:8000/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:1407:9)
    at HtmlBehaviorResource.create (http://localhost:8000/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:2693:47)error @ aurelia-logging-console.js:62log @ aurelia-logging.js:56error @ aurelia-logging.js:89processResult @ aurelia-router.js:1679(anonymous function) @ aurelia-router.js:1545f @ shim.min.js:1415(anonymous function) @ shim.min.js:1423b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
aurelia-logging-console.js:62 ERROR [app-router] Router navigation failed, and no previous location could be restored.
```

Importing up to four resources, I do not have any problem. If instead I try to load 5 or more resources, (ex. adding a router-view for the footer) I got the above error.

All the javascript files are empty like `export class NameClass { }`, just to test.

So the problem is, if I put all the footer html on global.html I do not have any issue. If I replace it with a router-view I will get the error above. Is a bug or I did something wrong?

PS: I opened the issue here because I think it is a binding problem, like I can see on the debug.

**Comment by jdanyow** [comment]
@vincenzoraco did any of the recent aurelia releases solve this problem for you?
