### ISSUE TITLE
Binding breaks when value converter parameters contain a backslash

### ISSUE THREAD

**Issue by mikeobrien** [aurelia/binding#182]
So any of the following:

```html
<tr repeat.for="x of y | converter: '\r'">
<tr repeat.for="x of y | converter: '\\d*'">
<tr repeat.for="x of y | converter: { regex: '\\d*' }">
```

Causes the following exception:

```
ERROR [app-router] TypeError: Cannot read property 'push' of undefined
    at Scanner.scanString (http://backoffice-dev.sentrichr.com/jspm_packages/github/aurelia/binding@0.9.1/aurelia-binding.js:2346:17)
    at Scanner.scanToken (http://backoffice-dev.sentrichr.com/jspm_packages/github/aurelia/binding@0.9.1/aurelia-binding.js:2210:23)
    at Lexer.lex (http://backoffice-dev.sentrichr.com/jspm_packages/github/aurelia/binding@0.9.1/aurelia-binding.js:2151:25)
    at new ParserImplementation (http://backoffice-dev.sentrichr.com/jspm_packages/github/aurelia/binding@0.9.1/aurelia-binding.js:2543:27)
    at Parser.parse (http://backoffice-dev.sentrichr.com/jspm_packages/github/aurelia/binding@0.9.1/aurelia-binding.js:2529:56)
    at SyntaxInterpreter.for (http://backoffice-dev.sentrichr.com/jspm_packages/github/aurelia/templating-binding@0.15.0/aurelia-templating-binding.js:159:117)
    at SyntaxInterpreter.interpret (http://backoffice-dev.sentrichr.com/jspm_packages/github/aurelia/templating-binding@0.15.0/aurelia-templating-binding.js:27:34)
    at TemplatingBindingLanguage.createAttributeInstruction (http://backoffice-dev.sentrichr.com/jspm_packages/github/aurelia/templating-binding@0.15.0/aurelia-templating-binding.js:272:46)
    at ViewCompiler.compileElement (http://backoffice-dev.sentrichr.com/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:2150:41)
    at ViewCompiler.compileNode (http://backoffice-dev.sentrichr.com/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:1944:23)
```

Remove the backslashes and its happy. Is there some special escaping for backslashes or is this a bug?

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this. It seems like there might be an issue in the parser.

**Comment by jdanyow** [comment]
working on it- looks like they haven't fixed this in the dart lexer either...

**Comment by mikeobrien** [comment]
Thx!

**Comment by mikeobrien** [comment]
Just tried it again and it works great. Thx again!
