### ISSUE TITLE
Binding errors since upgrade to 0.16

### ISSUE THREAD

**Issue by sickboy** [aurelia/binding#188]
I have a View and ViewModel, inside the View I have multiple compose elements with just a view="..." defined, and if.bind is bound to a boolean property.
~~~
        <div class="content">
          <compose view="components/_playlist_content.html"></compose>
        </div>
        <div class="expand au-animate" show.bind="isExpanded">
          <compose view="components/_playlist_expand.html"></compose>
        </div>
~~~
Inside these composed elements with custom views, I reference a property of the main ViewModel called: activeStateClass.
e.g: 
~~~
<template>
  <div class="play-footer-playlist basket basket-state-${activeStateClass}">
   ...
  </div>
</template>
~~~
if the boolean property changes to false, and the composed views disapppear, 
and then the boolean property changes back to true, and the composed views appear, I get the following errors:

~~~
Unhandled promise rejection TypeError: Cannot read property 'activeStateClass' of undefined
    at AccessScope.evaluate (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:1039:19)
    at InterpolationBinding.interpolate (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating-binding@0.16.0/aurelia-templating-binding.js:423:31)
    at InterpolationBinding.bind (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating-binding@0.16.0/aurelia-templating-binding.js:405:12)
    at View.bind (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:797:21)
    at ViewFactory.create (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:1791:14)
    at https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3663:36
    at h (https://local.withsix.net/cdn/js/vendor/libs.min.js?v=ToooCFxN7b6VCBp3BgJMmw4JdC8-4:9:8147)
    at https://local.withsix.net/cdn/js/vendor/libs.min.js?v=ToooCFxN7b6VCBp3BgJMmw4JdC8-4:9:8307
    at MutationObserver.l (https://local.withsix.net/cdn/js/vendor/libs.min.js?v=ToooCFxN7b6VCBp3BgJMmw4JdC8-4:8:13812)(anonymous function) @ browser-polyfill.js:2434
browser-polyfill.js:2434 Unhandled promise rejection TypeError: Cannot read property 'activeStateClass' of undefined(…)(anonymous function) @ browser-polyfill.js:2434
~~~

~~~
Unhandled promise rejection TypeError: Cannot read property 'activeStateClass' of undefined
    at AccessScope.evaluate (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:1039:19)
    at InterpolationBinding.interpolate (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating-binding@0.16.0/aurelia-templating-binding.js:423:31)
    at InterpolationBinding.bind (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating-binding@0.16.0/aurelia-templating-binding.js:405:12)
    at View.bind (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:797:21)
    at ViewFactory.create (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:1791:14)
    at https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3663:36
    at h (https://local.withsix.net/cdn/js/vendor/libs.min.js?v=ToooCFxN7b6VCBp3BgJMmw4JdC8-4:9:8147)
    at https://local.withsix.net/cdn/js/vendor/libs.min.js?v=ToooCFxN7b6VCBp3BgJMmw4JdC8-4:9:8307
    at MutationObserver.l (https://local.withsix.net/cdn/js/vendor/libs.min.js?v=ToooCFxN7b6VCBp3BgJMmw4JdC8-4:8:13812)(anonymous function) @ browser-polyfill.js:2434
~~~

~~~
Uncaught TypeError: Cannot read property '__observers__' of nullgetObserver @ aurelia-binding.js:3946observeProperty @ aurelia-binding.js:61connect @ aurelia-binding.js:1051bind @ aurelia-binding.js:4179bind @ aurelia-templating.js:2698bind @ aurelia-templating.js:802valueChanged @ if.js:55BindableProperty.createObserver.selfSubscriber @ aurelia-templating.js:2937call @ aurelia-templating.js:2809flushMicroTaskQueue @ aurelia-task-queue.js:110(anonymous function) @ aurelia-task-queue.js:60
~~~

If I remove the binding in the view to activeStateClass, I still get errors:

~~~
Unhandled promise rejection TypeError: Cannot read property '__observers__' of undefined
    at ObserverLocator.getObserver (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:3946:32)
    at Binding.observeProperty (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:61:41)
    at AccessScope.connect (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:1051:15)
    at AccessMember.connect (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:1093:19)
    at Binding.bind (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:4179:31)
    at View.bind (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:797:21)
    at ViewFactory.create (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:1791:14)
    at https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3663:36
    at h (https://local.withsix.net/cdn/js/vendor/libs.min.js?v=ToooCFxN7b6VCBp3BgJMmw4JdC8-4:9:8147)
    at https://local.withsix.net/cdn/js/vendor/libs.min.js?v=ToooCFxN7b6VCBp3BgJMmw4JdC8-4:9:8307(anonymous function) @ browser-polyfill.js:2434
browser-polyfill.js:2434 Unhandled promise rejection TypeError: Cannot read property '__observers__' of undefined(…)(anonymous function) @ browser-polyfill.js:2434
~~~

~~~
Unhandled promise rejection TypeError: Cannot read property '__observers__' of undefined
    at ObserverLocator.getObserver (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:3946:32)
    at Binding.observeProperty (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:61:41)
    at AccessScope.connect (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:1051:15)
    at AccessMember.connect (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:1093:19)
    at Binding.bind (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:4179:31)
    at View.bind (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:797:21)
    at ViewFactory.create (https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:1791:14)
    at https://local.withsix.net/cdn/aurelia/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3663:36
    at h (https://local.withsix.net/cdn/js/vendor/libs.min.js?v=ToooCFxN7b6VCBp3BgJMmw4JdC8-4:9:8147)
    at https://local.withsix.net/cdn/js/vendor/libs.min.js?v=ToooCFxN7b6VCBp3BgJMmw4JdC8-4:9:8307(anonymous function) @ browser-polyfill.js:2434
~~~

~~~
ncaught TypeError: Cannot read property '__observers__' of nullgetObserver @ aurelia-binding.js:3946observeProperty @ aurelia-binding.js:61connect @ aurelia-binding.js:1051bind @ aurelia-binding.js:4179bind @ aurelia-templating.js:2698bind @ aurelia-templating.js:802valueChanged @ if.js:55BindableProperty.createObserver.selfSubscriber @ aurelia-templating.js:2937call @ aurelia-templating.js:2809flushMicroTaskQueue @ aurelia-task-queue.js:110(anonymous function) @ aurelia-task-queue.js:60
console.ts:146
~~~

**Comment by sickboy** [comment]
As a temporary workaround I found that I can use show.bind, instead of if.bind.

**Comment by jdanyow** [comment]
related to https://github.com/aurelia/templating-resources/issues/117

**Comment by EisenbergEffect** [comment]
@jdanyow Is this fixed now?

**Comment by jdanyow** [comment]
yep
