### ISSUE TITLE
ERROR [app-router] TypeError: Cannot read property 'subscriberAdded' of undefined

### ISSUE THREAD

**Issue by stevies** [aurelia/binding#190]
When I use @bindable to bind an array of strings in my custom element, I get error:
```
ERROR [app-router] TypeError: Cannot read property 'subscriberAdded' of undefined
```
I've traced this back into aurelia-bindings.js
```
OoPropertyObserver.prototype.subscribe = function subscribe(context, callable) {
      if (this.addSubscriber(context, callable)) {
        this.obj.__observer__.subscriberAdded();
      }
};
```
where `this.obj.__observer__` is showing as undefined.

No such problem if I use array of objects.

Problem code can be seen in my sample app: https://github.com/stevies/aurelia-starter-kit

The @bindable array is at: 

https://github.com/stevies/aurelia-starter-kit/blob/master/app/src/resources/radio-switch/radio-switch.js#L6

When I feed it an array of strings - eg, from:

https://github.com/stevies/aurelia-starter-kit/blob/master/app/src/page1.js#L9

via 

https://github.com/stevies/aurelia-starter-kit/blob/master/app/src/page1.html

it breaks with the error above. No such problem with array of objects.

Of course, this could be my code - but it did work OK before the latest Aurelia upgrade.

Console log: 

```
ERROR [app-router] TypeError: Cannot read property 'subscriberAdded' of undefined
    at OoPropertyObserver.subscribe (http://localhost:9000/jspm_packages/github/aurelia/binding@0.10.1/aurelia-binding.js:3059:30)
    at InterpolationBinding.addObserver (http://localhost:9000/jspm_packages/github/aurelia/binding@0.10.1/aurelia-binding.js:47:16)
    at InterpolationBinding.observeProperty (http://localhost:9000/jspm_packages/github/aurelia/binding@0.10.1/aurelia-binding.js:62:17)
    at AccessMember.connect (http://localhost:9000/jspm_packages/github/aurelia/binding@0.10.1/aurelia-binding.js:1096:17)
    at Binary.connect (http://localhost:9000/jspm_packages/github/aurelia/binding@0.10.1/aurelia-binding.js:1364:17)
    at InterpolationBinding.interpolate (http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.16.0/aurelia-templating-binding.js:426:22)
    at InterpolationBinding.bind (http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.16.0/aurelia-templating-binding.js:405:12)
    at View.bind (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:797:21)
    at ViewFactory.create (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:1791:14)
    at BoundViewFactory.create (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:1660:31)error @ aurelia-logging-console.js:62log @ aurelia-logging.js:36error @ aurelia-logging.js:69processResult @ aurelia-router.js:1682(anonymous function) @ aurelia-router.js:1575f @ shim.min.js:1415(anonymous function) @ shim.min.js:1423b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600

```

**Comment by EisenbergEffect** [comment]
@jdanyow Can you take a look at this?

**Comment by jdanyow** [comment]
@stevies thanks for the detailed info- could you check one more thing for me- does the issue occur if you remove [this line](https://github.com/stevies/aurelia-starter-kit/blob/master/app/src/resources/radio-switch/radio-switch.html#L15)?

**Comment by stevies** [comment]
Yes, the error does go away.  But app still a bit broken in that my view is not showing the correct styles or markup from the custom element.  But that might be my code - I was fiddling around trying to fix the other problem and may have busted something in the process.  I'll double-check by reverting to a working version and re-doing the upgrades.  

Thanks for looking at this so quickly.  It is not affecting anything crucial for me.

**Comment by stevies** [comment]
Ah - of course - it is the line with: 
```
  <span>${item.text || item}</span>
```
that the styles get applied to and output the widget label.  Removing that completely is certainly going to screw my view.  

Is my code broken?  I easily can look at an alternative approach.  Or is it showing up some error in Aurelia?

**Comment by stevies** [comment]
This fixes it for me: 

```
        <template if.bind="!$parent.isArrayOfStrings()">
          <input  type="radio" name.bind="$parent.groupName"
                 model.bind="item" checked.bind="$parent.selected" disabled.bind="item.disabled">
          <span>${item.text}</span>
        </template>

        <template if.bind="$parent.isArrayOfStrings()">
          <input type="radio" name.bind="$parent.groupName"
               value.bind="item" checked.bind="$parent.selected">
          <span>${item}</span>
        </template>
```

**Comment by jdanyow** [comment]
@stevies thanks for checking- will get a fix in for this asap

```html
<template>
  <div repeat.for="item of items">
    ${item.text || item}
  </div>
</template>
```
```js
export class App {
  items = ['foo', 'bar', 'baz'];
}
```

**Comment by stevies** [comment]
Thanks again.
