### ISSUE TITLE
Binding error with ref attributes within child html templates

### ISSUE THREAD

**Issue by Markusxmr** [aurelia/binding#335]
Greetings, 
When navigating to a route that contains nested html element with a ref attribute, and then navigating to another route, console logs 
```
Uncaught (in promise) TypeError: Cannot read property 'parent' of null(…)
```
Here is the repo and the "culprit" line 
[ref-attribute-issue](https://github.com/Markusxmr/Binding-behaviour/blob/master/src/modules/users/components/sub-element.html#L2)

Issue occured after the latest updates.

**Comment by jdanyow** [comment]
hey @Markusxmr- thanks for letting us know- what's the stack trace for that error?

**Comment by Markusxmr** [comment]
On the repo I linked console logs
```
aurelia-binding.js:1265 Uncaught (in promise) TypeError: Cannot read property 'parent' of null
    at AccessScope.evaluate (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.2.2/aurelia-binding.js:1265:21)
    at AccessMember.assign (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.2.2/aurelia-binding.js:1306:34)
    at NameBinder.unbind (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.2.2/aurelia-binding.js:4965:29)
    at View.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1045:23)
    at Controller.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:2961:21)
    at View.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1050:26)
    at Controller.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:2961:21)
    at View.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1050:26)
    at ViewSlot.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1349:24)
    at View.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1055:23)
```
and in the app where I encounterd the issue
```
aurelia-binding.js:1265 Uncaught (in promise) TypeError: Cannot read property 'parent' of null
    at AccessScope.evaluate (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.2.2/aurelia-binding.js:1265:21)
    at AccessMember.assign (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.2.2/aurelia-binding.js:1306:34)
    at NameBinder.unbind (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.2.2/aurelia-binding.js:4965:29)
    at View.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1045:23)
    at Controller.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:2961:21)
    at View.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1050:26)
    at Controller.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:2961:21)
    at View.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1050:26)
    at If.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.1.3/if.js:68:17)
    at Controller.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:2965:26)
```

**Comment by EisenbergEffect** [comment]
Try running `jspm update` and see if that fixes it for you. We recently had a patch release covering a bug in this exact method.

**Comment by Markusxmr** [comment]
jspm update to latest aurelia modules, did not fix the issue. It took me some time track it, and by refactoring the code, bypassed the issue. But original issue does remain

**Comment by EisenbergEffect** [comment]
Can you please create a repro on the skeleton of us? If you can attach the
src folder to this ticket we can probably get it fixed.

**Comment by Markusxmr** [comment]
I did, in my first post. Gues "ref-attribute-issue" is not most intuitive name :smile: 
[skeleton-repo](https://github.com/Markusxmr/Binding-behaviour/blob/master/src/modules/users/components/sub-element.html#L2)

**Comment by EisenbergEffect** [comment]
Oops. Sorry :) We will take a look shortly.

**Comment by Markusxmr** [comment]
No prob. Eh, sundays :smile:

**Comment by jdanyow** [comment]
Simple repro based on @Markusxmr's example:  https://gist.run/?id=421475231db224f6d18cdf4c2b16e843

The ref is being put on a bindable property.  Not sure if this is a supported scenario.

**Comment by jdanyow** [comment]
Closing this- not a supported use-case for ref binding.

**Comment by Markusxmr** [comment]
Ok.
