### ISSUE TITLE
Binding to Namespaced Attributes

### ISSUE THREAD

**Issue by paullryan** [aurelia/binding#34]
When bind to attributes(one-way) there are a couple of options you can either bind with attr-name.bind="variable" (also tried one-way and one-time) or using interpolation attr-name="${variable}", either way though if you try to bind to a namespaced element such as xlink:href you currently get:

```bash
Uncaught NamespaceError: Failed to execute 'setAttributeNS' on 'Element': '' is an invalid namespace for attributes.
```

For have the following in a controller page.js:

```javascript
export class page {
	constructor(){
		this.icon = 'blah';
	}
}
```
and the following in page.html:
```html
<template>
  <svg class="icon ${icon}">
    <use xlink:href="${icon}"></use>
  </svg>
</template>
```

As I said either of the bind's above is throwing the given error. It appears that the bug is in property-observation, in that the observer is either setting to a raw attribute or a null namespaced attribute which is causing the error.

**Comment by paullryan** [comment]
I instrumented the bootstrap handleApp function to print the  full stack trace:

```bash
Error: Failed to execute 'setAttributeNS' on 'Element': '' is an invalid namespace for attributes.
    at Error (native)
    at OoPropertyObserver.setValue (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.3/system/property-observation.js:200:26)
    at InterpolationBinding.setValue (http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.8.4/system/binding-language.js:214:35)
    at InterpolationBinding.bind (http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.8.4/system/binding-language.js:202:22)
    at View.bind (http://localhost:9000/jspm_packages/github/aurelia/templating@0.8.9/system/view.js:65:29)
    at ViewFactory.create (http://localhost:9000/jspm_packages/github/aurelia/templating@0.8.9/system/view-factory.js:173:22)
    at BoundViewFactory.create (http://localhost:9000/jspm_packages/github/aurelia/templating@0.8.9/system/view-factory.js:128:39)
    at Repeat.processItems (http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.8.6/system/repeat.js:105:36)
    at Repeat.bind (http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.8.6/system/repeat.js:60:22)
    at BehaviorInstance.bind (http://localhost:9000/jspm_packages/github/aurelia/templating@0.8.9/system/behavior-instance.js:67:39)
```

Also if I hack the property-observation code to explicitly set the namespace it works, but this is really kludgy and likely to break quickly.

https://github.com/aurelia/binding/blob/master/src/property-observation.js#L153-L159 changed to:
```javascript
  setValue(newValue) {
    if (this.isSVG) {
      if(this.propertyName.indexOf('xlink:') >= 0){
        this.obj.setAttributeNS("http://www.w3.org/1999/xlink", this.propertyName, newValue);
      } else {
        this.obj.setAttributeNS(null, this.propertyName, newValue);
      }
    } else {
      this.obj[this.propertyName] = newValue;
    }
  }
```

**Comment by paullryan** [comment]
Something like the following will work for the interpolation case:

``` javascript
function getAttrNamespace(attributes, propertyName){
  let attr = attributes.getNamedItem(propertyName);
  if(attr){
    return attr.namespaceURI;
  }
}

setValue: {
  if (this.isSVG) {
    if(this.propertyName.indexOf(':') > 0){
      let namespaceURI = getAttrNamespace(this.obj.attributes, this.propertyName);
      this.obj.setAttributeNS(namespaceURI, this.propertyName, newValue);
    } else {
      this.obj.setAttributeNS(null, this.propertyName, newValue);
    }
  } else {
    this.obj[this.propertyName] = newValue;
  }
},
```
But not for the bind case because even if you grab `propertyname + ".bind"` it won't be bound to the desired namespaceURI yet so you may have to do a global lookup somehow of the the namespaces available to the document.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this and see if we can do work to improve this, possibly through our element observer abstraction?

**Comment by jdanyow** [comment]
sure

**Comment by jdanyow** [comment]
Still researching this.  Posted related question here:  http://stackoverflow.com/questions/28560100/why-is-getattributenodens-returning-null
