### ISSUE TITLE
Reseting an array bound to view-model.ref throws an exception

### ISSUE THREAD

**Issue by Vaccano** [aurelia/binding#361]
If I have a custom element setup like this:

      <div repeat.for="box of boxes">
        <box box.bind="box" view-model.ref="boxViewModels[$index]"></box>
      </div>

and I set `boxes` to be `[]`, then I get the following exception:

>TypeError: Cannot read property 'boxViewModels' of null at AccessScope.evaluate

Here is the [gist run](https://gist.run/?id=30f77471ffeee12863a5) for this issue.
Load it up and press the "Clear All" button to see it in action.  

If there is a workaround to this issue, I would love to know it.  (It has me stuck)

**Comment by Vaccano** [comment]
Incase it is useful, here is the call stack:

<pre>"TypeError: Cannot read property 'boxViewModels' of null 
at AccessScope.evaluate (aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js:1362:21) 
at AccessKeyed.assign (aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js:1448:34) 
at NameBinder.unbind (aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js:5042:29) 
at View.unbind (aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js:959:23) 
at ViewFactory.returnViewToCache (aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js:1846:14) 
at View.returnToCache (aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js:872:24) 
at removeAction (aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js:1321:16) 
at ViewSlot.removeAt (aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js:1336:14) 
at Repeat.removeView (aurelia-templating-resources@1.0.0-beta.1.2.0/repeat.js:246:28) 
at ArrayRepeatStrategy._runSplices (aurelia-templating-resources@1.0.0-beta.1.2.0/array-repeat-strategy.js:139:38)"</pre>

**Comment by cehoffman** [comment]
I think this PR will fix it aurelia/templating#306

**Comment by Vaccano** [comment]
@cehoffman This issue is indeed fixed by that PR.  This is a duplicate of https://github.com/aurelia/framework/issues/372.
