### ISSUE TITLE
Stuff broke in 1.3.2 when using kendo bridge

### ISSUE THREAD

**Issue by Souldrinker** [aurelia/binding#377]
Not sure if I should post it here or in the aurelia-kendoui-bridge, but since it broke after updating this library I try here first.

After doing a jspm update this morning after the Aurelia Mid April 2016 Patch Update things stopped working. When I reinstalled aurelia-binding 1.3.1 (without ^) and manually downgraded the config.js to use that version and left everything else upgraded things started working again. The aurelia-kendoui-bridge library is still unchanged at 0.7.1 both before and after the updates today, so I guess something have changed more than just linting in aurelia-binding 1.3.2?

For example in one of my views where I have a kendo grid (using the Aurelia bridge) I do something like this in attached ```setTimeout(() => this.grid.hideColumn("myColumn")}, 0);``` where grid is declared using ```k-widget.bind="grid"``` in my ak-grid in the view which has always worked before, but now after the latest update the grid is undefined.

One of my other views on the same page (that is also using a kendo grid) refuses to show up at all and in the browser console I get this stack trace:
```
es6.promise.js:134 Unhandled promise rejection TypeError: Cannot read property 'toString' of undefined
    at autoConvertAdd (http://localhost:4703/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.2/aurelia-binding.js:1916:21)
    at Binary.evaluate (http://localhost:4703/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.2/aurelia-binding.js:1701:18)
    at evalList (http://localhost:4703/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.2/aurelia-binding.js:1907:33)
    at ValueConverter.evaluate (http://localhost:4703/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.2/aurelia-binding.js:1271:50)
    at ChildInterpolationBinding.bind (http://localhost:4703/jspm_packages/npm/aurelia-templating-binding@1.0.0-beta.1.2.1/aurelia-templating-binding.js:228:36)
    at View.bind (http://localhost:4703/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:912:21)
    at TemplatingEngine.enhance (http://localhost:4703/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:4130:12)
    at TemplateCompiler.enhanceView (http://localhost:4703/jspm_packages/npm/aurelia-kendoui-bridge@0.7.1/common/template-compiler.js:100:40)
    at _loop (http://localhost:4703/jspm_packages/npm/aurelia-kendoui-bridge@0.7.1/common/template-compiler.js:86:18)
    at TemplateCompiler.compile (http://localhost:4703/jspm_packages/npm/aurelia-kendoui-bridge@0.7.1/common/template-compiler.js:91:9)
    at TemplateCompiler.handleTemplateEvents (http://localhost:4703/jspm_packages/npm/aurelia-kendoui-bridge@0.7.1/common/template-compiler.js:47:16)
    at kendo.ui.Widget.angular (http://localhost:4703/jspm_packages/npm/aurelia-kendoui-bridge@0.7.1/common/template-compiler.js:24:15)
    at X.extend._angularItems (http://localhost:4703/vendors/js/kendo.core.min.js:26:1151)
    at ue.ui.DataBoundWidget.extend._angularItems (http://localhost:4703/vendors/js/kendo.grid.min.js:28:16540)
    at .<anonymous> (http://localhost:4703/vendors/js/kendo.grid.min.js:28:15952)
    at P.extend._muteAngularRebind (http://localhost:4703/vendors/js/kendo.core.min.js:26:1009)
```

**Comment by stoffeastrom** [comment]
I [compared](https://github.com/aurelia/binding/compare/1.0.0-beta.1.3.1...1.0.0-beta.1.3.2#diff-25609766b4c70f522aa0041b479511c7) the tags. Search for `autoConvertAdd`. Looks like it changed to strict comparison. Might be a problem?

**Comment by jdanyow** [comment]
I agree with @stoffeastrom.  @Souldrinker can you confirm that reverting only the `autoConvertAdd` function to 1.3.1 resolves the issue for you?  

Maybe we need to add support for `undefined` in there?

**Comment by Souldrinker** [comment]
Yup, just changing the === to == and !== to != in the autoConvertAdd method in aurelia-binding.js (1.3.2) seemed to fix it.

**Comment by jdanyow** [comment]
one last thing (I want to make sure we add unit tests for the right scenario):

when the error occurs, one or both of the arguments to the `autoConvertAdd` are `undefined`, causing the issue.  Do I have that right?

**Comment by Souldrinker** [comment]
Yup, in one of the calls to that method b was undefined.

In that case I got ```a = "widgets.vm.logbook.status-", b = undefined``` which seems to come from this i18next value converter inside a Kendo grid:
```
<ak-template>
    ${"widgets.vm.logbook.status-" + status | t}
</ak-template>
```
...which then seems to make all Kendo stuff break.

But I suppose concatenating a string with an undefined value should work?

**Comment by jdanyow** [comment]
fixed in https://github.com/aurelia/binding/commit/d2a88ddc79305d761be1b1efba666da007943cb7 but I jammed up the issue number on the commit message :sob:

**Comment by AdamWillden** [comment]
@jdanyow I've just come across this issue moving from 1.3.1 to 1.3.2 but I'm not using kendo. Thanks for already fixing this, any ideas when we may have a release with this fix included? I understand the releases need syncing to include this.

**Comment by flieks** [comment]
@jdanyow @AdamWillden I have the same problem. b being null and toString() crashing.
```
BehaviorPropertyObserver.prototype.setValue = function setValue(newValue) {
      var oldValue = this.currentValue;

      if (oldValue !== newValue) {
        if (this.publishing && this.notqueued) {
          this.notqueued = false;
          this.taskQueue.queueMicroTask(this);
        }

        this.oldValue = oldValue;
        this.currentValue = newValue;
      }
    };
```
so newValue is null. Can't find more info about it

Thanks

**Comment by flieks** [comment]
i narrowed down the problem/bug:
it happens when you make global.value null (=global scope)

```
 <compose containerless if.bind="global.value" 
     view-model.bind="'components/' + global.value  + '/index'" 
     model.bind="global.model" 
    ></compose>
```

So the if.bind should be checked right before the bind is executed..

I'm making it null in a callback of request to server in the bind() of another custom element CE.
I moved that request to the attached() in CE and now it all works.
