### ISSUE TITLE
Unable to parse attached behavior's options

### ISSUE THREAD

**Issue by bfil** [aurelia/binding#5]
When enabling options on an attached behaviour an exception is thrown when the attribute is being parsed.

The following example is trying to expose an option called `replace`, for the `spinner` attached behavior:

    static metadata(){ return Behavior.attachedBehavior('spinner').withOptions().withProperty('value', 'valueChanged').withProperty('replace'); }

When the behavior above is used in a template, like so:

    spinner.bind="value.bind: spinning; replace: true"

the parsing of the attribute fails, the stack trace is the following:

    Potentially unhandled rejection [2] Error: Parser Error: Unexpected token : at column 11 in [value.bind: spinning; replace: true]
    at ParserImplementation.error (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/parser.js:470:21)
    at ParserImplementation.parsePrimary (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/parser.js:365:22)
    at ParserImplementation.parseAccessOrCallMember (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/parser.js:306:33)
    at ParserImplementation.parsePrefix (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/parser.js:297:29)
    at ParserImplementation.parseMultiplicative (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/parser.js:270:33)
    at ParserImplementation.parseAdditive (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/parser.js:252:33)
    at ParserImplementation.parseRelational (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/parser.js:230:33)
    at ParserImplementation.parseEquality (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/parser.js:208:33)
    at ParserImplementation.parseLogicalAnd (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/parser.js:194:33)
    at ParserImplementation.parseLogicalOr (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/parser.js:180:33)

I tried different combinations in the attribute content, but the parser apparently does not like the ':' character.

**Comment by EisenbergEffect** [comment]
Ok, I think this is an example of the effects of my poor documentation ;) I tested this in the navigation skeleton and it appears to work. I see some errors in your code, so I will put the correct code and markup below and then hopefully you can try that out and see if it works for your too.

In your behavior, you need to define the properties as part of the options, like this:

```javascript
static metadata(){ 
  return Behavior
    .attachedBehavior('spinner')
    .withOptions().and(x => {
        x.withProperty('value', 'valueChanged')
         .withProperty('replace');
      });
```

Then, you don't use the "bind" on the behavior itself, but rather on the individual options:

```markup
spinner="value.bind: spinning; replace: true"
```

See if that does it for you.

**Comment by bfil** [comment]
If I change it to the way you provided, I don't get any error (which is good).
But then both properties (value and replace) are undefined, any idea why that might be?

**Comment by EisenbergEffect** [comment]
When/where are you attempting to access their values?

**Comment by bfil** [comment]
In the `attached()` method, or even after that, they don't appear to get set.

**Comment by EisenbergEffect** [comment]
Really? Something else is going on here. Is there any chance you can send me a streamlined version of your app that I can take a look at?

**Comment by bfil** [comment]
Sure, I'll send it over on Gitter
