### ISSUE TITLE
Using @children at a property level logs a warning

### ISSUE THREAD

**Issue by tochoromero** [aurelia/binding#567]
I have a CustomElement that uses the children annotation, like this:
`@children('aubs-tabs') tabs = []`

Everything works just fine, but it logs the following in the console:
`WARN [property-observation] Cannot observe property 'tabs' of 'AubsTabsetCustomElement'`

Now, the warning goes away if I use the children annotation at a class level:
`@children({ name: "tab", selector: "aubs-tab" })`

I did some debugging and that warn is being logged here: https://github.com/aurelia/binding/blob/1d6e826dbbc401ca21ad0deaf7acca498cd71c8b/src/property-observation.js#L104

And I believe this is the root cause:
`Uncaught TypeError: Cannot redefine property: tabs
    at Function.defineProperty (<anonymous>)
    at eval (eval at evaluate (:117:21), <anonymous>:1:8)
    at SetterObserver.convertProperty (http://localhost/aurelia/aurelia.bundle.js:5087:5)
    at SetterObserver.subscribe (http://localhost/aurelia/aurelia.bundle.js:5072:12)
    at Binding.addObserver (http://localhost/aurelia/aurelia.bundle.js:1560:14)
    at Binding.observeProperty (http://localhost/aurelia/aurelia.bundle.js:1575:15)
    at AccessScope.connect (http://localhost/aurelia/aurelia.bundle.js:2843:13)
    at Binding.connect (http://localhost/aurelia/aurelia.bundle.js:6305:27)
    at enqueueBindingConnect (http://localhost/aurelia/aurelia.bundle.js:1640:13)
    at Binding.bind (http://localhost/aurelia/aurelia.bundle.js:6272:7)
    at Controller.bind (http://localhost/aurelia/aurelia.bundle.js:10735:17)
    at View.bind (http://localhost/aurelia/aurelia.bundle.js:8779:22)
    at Controller.bind (http://localhost/aurelia/aurelia.bundle.js:10757:17)
    at View.bind (http://localhost/aurelia/aurelia.bundle.js:8779:22)
    at Controller.bind (http://localhost/aurelia/aurelia.bundle.js:10757:17)
    at View.bind (http://localhost/aurelia/aurelia.bundle.js:8779:22)`

Fortunately, there is an easy workaround, but I wonder why it only happens with property level annotations.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into why this is happening? There shouldn't be a warning for this.

**Comment by jdanyow** [comment]
Babel's decorator logic makes the property not configurable: https://github.com/aurelia/binding/issues/406

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/templating #520](https://github.com/aurelia/templating/issues/520) via [**ZenHub**](https://www.zenhub.com/)
